---
language: node_js
before_install:
  - dpkg --compare-versions `npm -v` ge 7.10 || npm i -g npm@^7.10
  - npm --version
cache:
  directories:
    - "node_modules"
env:
  global:
    - SCRIVITO_TENANT: "1234567890abcdef1234567890abcdef"
  matrix:
    - TASK: "build"
    - TASK: "eslint"
    - TASK: "es-check"
script: npm run $TASK
